#### general settings
name: LunaTokis_scratch_b16p32f5b40n7l1_600k_Vimeo
use_tb_logger: false #true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [4]

#### datasets
datasets:
  train:
    name: Adobe
    mode: Adobe # Vimeo7 & Adobe
    interval_list: [1]
    random_reverse: true #false
    border_mode: false
    # dataroot_GT: /data/nnice1216/vimeo_septuplet/zoomin/HR/
    # dataroot_LQ: /data/nnice1216/vimeo_septuplet/zoomin/LR/
    dataroot_GT: /home/users/zeyuan_chen/adobe240fps/HR/
    dataroot_LQ: /home/users/zeyuan_chen/adobe240fps/LR/
    # dataroot_GT: /mnt/data/t
    # dataroot_LQ: /mnt/data/
    cache_keys: Vimeo7_train_keys.pkl 

    N_frames: 7
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 18
    GT_size: 192
    LQ_size: 48
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: LIIF # LunaTokis & LIIF & TMNet & LIIF_test1 & LIIF_test2
  nf: 64
  nframes: 7
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 40
  HR_in: false

#### path
path:
  pretrain_model_G: ~ 
  strict_load: false #true #
  resume_state: ~
  models: /home/users/zeyuan_chen/model_repo/models-shic0e6bbf/
  training_state: /home/users/zeyuan_chen/model_repo/training_state-shic0e6bbf/

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-5
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
